jobs:
  plan:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run:
          name: terraform fmt
          command: |
            ls
            terraform init
            terraform fmt
      - run:
          name: terraform plan
          command: terraform plan -out plan
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./terraform
            - plan
  apply:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: terraform apply
          command: terraform apply

workflows:
  version: 2
  build_plan:
    jobs:
      - plan
      - apply:
          requires:
            - plan
