jobs:
  plan:
    docker:
      - image: hashicorp/terraform:0.12.29
    steps:
      - checkout
      - run:
          name: terraform fmt
          command: |
            terraform init
            terraform fmt
      - run:
          name: terraform plan
          command: terraform plan -out plan
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./
  apply:
    docker:
      - image: hashicorp/terraform:0.12.29
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: terraform apply
          command: terraform apply -auto-approve

workflows:
  version: 2
  build_plan:
    jobs:
      - plan
      - review_plan:
          requires:
            - plan
          type: approval
          filters:
            branches:
              ignore: master
      - apply:
          requires:
            - plan
          filters:
            branches:
              only: master
