jobs:
  build:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run:
          name: terraform fmt
          command: |
            terraform init
            terraform fmt
