jobs:
  build:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run:
          name: terraform fmt
          command: |
            terraform init
            terraform fmt
  plan:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run:
        name: terraform plan
        command: |
          terraform plan

workflows:
  version: 2
  build_plan:
    jobs:
      - build
      - plan
